import './globals.css'
import { Inter } from 'next/font/google'
import {TasksProvider} from '../context/TasksContext'
const inter = Inter({ subsets: ['latin'] })
import Navbar from '../components/Navbar'
import { Toaster } from './Toaster'
export const metadata = {
  title: 'Task App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TasksProvider>
          <div className='bg-gray-900 text-white h-[calc(100vh-0rem)]'>
            <main className='h5/6 px-28 py-10'>
          <Navbar />
          {children}
          <Toaster />
          </main>
          </div>
        </TasksProvider>
      </body>
    </html>
  )
}
